name: Feature branch workflow

on:
  push:
    paths:
      - .github/**
      - src/**
      - tests/**
      - demos/**
    branches-ignore:      
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TEST_REDDIT_USERNAME: ${{ secrets.TEST_REDDIT_USERNAME }}
      TEST_REDDIT_FRIEND_USERNAME1: ${{ secrets.TEST_REDDIT_FRIEND_USERNAME1 }}
      TEST_REDDIT_FRIEND_USERNAME2: ${{ secrets.TEST_REDDIT_FRIEND_USERNAME2 }}
      TEST_REDDIT_PASSWORD: ${{ secrets.TEST_REDDIT_PASSWORD }}
      TEST_REDDIT_CLIENT_ID: ${{ secrets.TEST_REDDIT_CLIENT_ID }}
      TEST_REDDIT_CLIENT_SECRET: ${{ secrets.TEST_REDDIT_CLIENT_SECRET }}
      TEST_SUBREDDIT_NAME: ${{ secrets.TEST_SUBREDDIT_NAME }}
      TEST_MULTIREDDIT_NAME: ${{ secrets.TEST_MULTIREDDIT_NAME }}

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.402'

    - name: Restore packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --verbosity normal --configuration Release /p:CollectCoverage=true /p:CoverletOutput='./' /p:CoverletOutputFormat=opencover      

    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 